---
title: "Data Parse"
author: "Team"
date: "February 13, 2016"
output: html_document
---



Statistics
```{r}
test = function(crazyf, month, Unique_Complaints){
#Have to add months to columns
month_clean <- data.frame(do.call('rbind', strsplit(as.character(crazyf$Date),"-")))
colnames(month_clean) = c("Year", "Month", "Day")
Complaints_total_grid = cbind(crazyf, month_clean)
Complaints_total_grid$Month = as.numeric(Complaints_total_grid$Month)


group.Month <- group_by(Complaints_total_grid[,c("Month", "Complaint.Type")], Month,Complaint.Type)
Sum_group_Month<- summarise(group.Month,count = n())

#Create matrix to store statistics
stat_store = matrix(0, ncol = length(unique(Complaints_total_grid$Complaint.Type)), nrow = 36)
stat_store = as.data.frame(stat_store)
colnames(stat_store) = unique(Complaints_total_grid$Complaint.Type)

#Loop through all and calculate 
for(i in Unique_Complaints){
  index = 1
  filtered = filter(Complaints_total_grid, Complaint.Type == i)
  count = 1
  for(j in c(1:12)){
    filtered_month = filter(filtered, Month == j)
    quantiles = quantile(filtered_month$count, c(.10, .50, .90))
    stat_store[c((count):(count+2)),i] = quantiles
    count = count + 3
  }
  index = index + 1

}

top_stat_store = stat_store[,Unique_Complaints]

#Filter on month 
test = month
#start_date = "2015-02-01"

end_date = "2015-02-28"
month_fiter = filter(Complaints_total_grid[,c("Date","Month", "Complaint.Type", "count")],Month == test & Complaint.Type %in% Unique_Complaints)
group.Month <- group_by(month_fiter, Month,Complaint.Type)
Sum_group_Month<- summarise(group.Month,avg = mean(count))

#Filter for Jan
Jan = top_stat_store[1:3,]
Feb = top_stat_store[4:6,]
Mar = top_stat_store[7:9,]
Apr = top_stat_store[10:12,]
May = top_stat_store[13:15,]
Jun = top_stat_store[16:18,]
Jul = top_stat_store[19:21,]
Aug = top_stat_store[22:24,]
Sep = top_stat_store[25:27,]
Oct = top_stat_store[28:30,]
Nov = top_stat_store[31:33,]
Dec = top_stat_store[34:36,]

if( month == 1){
    Calc = Jan
}else if( month == 2){
    Calc = Feb
}else if( month == 3){
    Calc = Mar

}else if( month == 4){
    Calc = Apr

}else if( month == 5){
    Calc = May

}else if( month == 6){
  Calc = Jun
  
}else if( month == 7){
  Calc = Jul
  
}else if( month == 8){
  Calc = Aug
  
}else if( month == 9){
  Calc = Sep
  
}else if( month == 10){
  Calc = Oct
  
}else if( month == 11){
  Calc = Nov
  
}else {
  Calc = Dec
}

#Create color matrix for heat map
Jan_color = Feb[1,]
colnames(Jan_color)

for( i in Sum_group_Month$Complaint.Type){
  month_fiter2 = filter(Sum_group_Month,Complaint.Type == i)
  if(month_fiter2$avg<Calc[,i][1]){
    Jan_color[1,i] = 1
  }else if(month_fiter2$avg<Calc[,i][2]){
    Jan_color[1,i] = 2
  }else if(month_fiter2$avg<Calc[,i][3]){
    Jan_color[1,i] = 3
  }else{
    Jan_color[1,i] = 4
  }
}
    
a = data.frame(t(Jan_color))
a$Complaints = rownames(a)
colnames(a) = c("Health", "Complaints")
rownames(a) = c(1:nrow(a))
return (a)
}

```

```{r}
df = readRDS("full_filtered.rds")

df$Complaint.Type[df$Complaint.Type == "HEATING"] = "HEAT/HOT WATER"

All.Date.Complaint <- group_by(df, Date,Complaint.Type)
Complaints_total <- summarise(All.Date.Complaint,count = n())
Unique_Complaints = unique(df$Complaint.Type)
bur = as.character(unique(df$Borough))

month_clean <- data.frame(do.call('rbind', strsplit(as.character(df$Date),"-")))
colnames(month_clean) = c("Year", "Month", "Day")
Complaints_total_grid_df = cbind(df, month_clean)
Complaints_total_grid_df$Month = as.numeric(Complaints_total_grid_df$Month)

All <- group_by(Complaints_total_grid_df, Month,Complaint.Type)
Complaints_Month <- summarise(All,count = n())

# Complaints_Month_filtered = filter(Complaints_Month, Month == 1)
# Filter_Index = order(Complaints_Month_filtered$count, decreasing = TRUE)
# Complaint.Type_filtered = Complaints_Month[Filter_Index[1:10],]
# Unique_Complaints = as.character(Complaint.Type_filtered$Complaint.Type)

b = data.frame()
a = data.frame()
for(j in c(1:12)){
  #Need to filter Unique Complaints for the Month
  Complaints_Month_filtered = filter(Complaints_Month, Month == j)
  Filter_Index = order(Complaints_Month_filtered$count, decreasing = TRUE)
  Complaint.Type_filtered = Complaints_Month_filtered[Filter_Index[1:10],]
  Unique_Complaints = as.character(Complaint.Type_filtered$Complaint.Type)

  for(i in bur){
    input = filter(df, Borough == i)
    All.Date.Complaint <- group_by(input, Date,Complaint.Type)
    Complaints_total <- summarise(All.Date.Complaint,count = n())
    a = test(Complaints_total, j,Unique_Complaints)
    a$Borough = i
    a$Month = j
    b = rbind(b,a)
  }
}
```

```{r}
c = filter(b, Month == 6)
ggplot(c, aes(Borough, Complaints)) + 
  geom_tile(aes(fill = Health), colour = "white")  +
  scale_fill_gradient(low = "LightSkyBlue", high = "LightCoral", na.value = "grey", limits=c(1, 4))
  #theme(axis.ticks = element_line(size = 0), axis.text.x = element_text(size = 0)) + 

```

